#!/bin/bash
abs_path () {
    if [ -d $1 ]; then
	TMPDIR=$1
    else
	TMPDIR=`dirname $1`
    fi
    PSTR=`cd ${TMPDIR} && pwd -P`
    echo $PSTR
}

IP=/sbin/ip
DATADIR=`abs_path $0`
NETADD=10.10.25
NETGWHW=00:12:44:42:70:00
IFNAME=eth1

if [[ "$1" && `zcat $DATADIR/macadd.dat | grep $NETADD.$1` ]]; then
	ipv4=$1
else
	ipv4=240
fi

addmsg=`zcat $DATADIR/macadd.dat | grep $NETADD.$ipv4`
mac=`echo $addmsg | awk '{print $2}'`

echo "Shutting down $IFNAME ..."
${IP} link set $IFNAME down
${IP} addr flush dev ${IFNAME}
## Change ethernet name to $IFNAME ?
#${IP} link set dev eth1 name $IFNAME

sleep 1

echo "Raising up $IFNAME using $NETADD.$ipv4 with $mac ..."
${IP} link set $IFNAME address $mac
${IP} addr add $NETADD.$ipv4 dev $IFNAME
${IP} link set $IFNAME up

echo 
echo "ARP setting ..."
${IP} neigh add $NETADD.10 lladdr $NETGWHW dev $IFNAME

echo 
echo "Add default route -- $NETADD.10 ..."
${IP} route add $NETADD.10 dev $IFNAME
${IP} route add default via $NETADD.10

