#!/bin/bash

IP=/sbin/ip

${IP} link set eth0 down
${IP} link set eth1 down

${IP} link set eth0 address 78:2b:cb:93:81:a2
${IP} link set eth1 address 00:e0:4c:53:44:58

${IP} addr flush dev eth0
${IP} addr replace 192.0.31.201/24 broadcast 192.0.31.255 dev eth0

${IP} link set eth0 up
${IP} link set eth1 up
