#!/bin/bash
IFCONF=/sbin/ifconfig
DATADIR=/opt/ip-switch
NETADD=10.10.25
NETGWHW=00:12:44:42:70:00
#IFNAME=usbnet0
IFNAME=eth1

if [[ "$1" && `zcat $DATADIR/macadd.dat | grep $NETADD.$1` ]]; then
	ip=$1
else
	ip=233
fi

## Change default ethernet name
#if [[ $IFNAME == "usbnet0" ]]; then
#    echo "Renaming ethernet to usbnet0 ..."
#    nameif -c $DATADIR/mactab
#fi

addmsg=`zcat $DATADIR/macadd.dat | grep $NETADD.$ip`
mac=`echo $addmsg | awk '{print $2}'`

echo "Shutting down $IFNAME ..."
$IFCONF $IFNAME down
sleep 1
echo "Raising up $IFNAME using $NETADD.$ip with $mac ..."
$IFCONF $IFNAME hw ether $mac
$IFCONF $IFNAME $NETADD.$ip netmask 255.255.255.0 up

echo 
echo "ARP setting ..."
/usr/sbin/arp -i $IFNAME -s $NETADD.10 $NETGWHW

echo 
echo "Add default route -- $NETADD.10 ..."
/sbin/route add default     gw $NETADD.10 $IFNAME

#echo 
#echo "Delete route -- 192.0.31.* ..."
#sleep 2
#/sbin/route del default gateway 192.0.31.254

# GFW
#echo "Add rules for GFW ..."
#/usr/sbin/ipset -R < /opt/ip-switch/ipset.rules
#/sbin/iptables-restore < /opt/ip-switch/iptables.rules

